### ISSUE TITLE
7. Admin removes member (TJ's)

### ISSUE THREAD

**Issue by janjakovacevic** [david-fisher/320-S19-Track2#11]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Steveo539** [comment]
Fred is an admin of Members Only. Fred notices Hank, a member of Members Only, has been posting photos he deemed inappropriate and even illegal. Fred then uses the ‘Remove Member’ option on Hank’s profile to remove him from the Members Only community. From now on, Hank may no longer log on to the Members Only platform.
