### ISSUE TITLE
8. Member reverses/removes a filter (TJ's)

### ISSUE THREAD

**Issue by janjakovacevic** [david-fisher/320-S19-Track2#12]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Steveo539** [comment]
Fred is a member of Members Only. Fred recently posted a photo of his latest vacation with a filter he really liked. Days later, Fred decides he no longer likes the photo, so he uses the ‘Remove Filter’ option under the photo to remove the filter from the photo. From now on, the original post of Fred’s vacation will no longer have the original filter.
