### ISSUE TITLE
9. Member posts comments on a photo (TJ's)

### ISSUE THREAD

**Issue by janjakovacevic** [david-fisher/320-S19-Track2#13]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Steveo539** [comment]
Fred is a member of Members Only. One day while browsing through the Members Only homepage, Fred notices a photo of a beautiful landscape. Interested to find the location of this landscape, Fred decides to ask the author of this post where the photo was shot. Fred uses the ‘Comment’ button that opens up a keyboard prompt for him to enter his question. Fred then types his question in the text field and presses ‘Enter’ on his keyboard. Fred’s question is then displayed in text underneath the photo to be displayed to the author, as well as all of his followers of the Members Only community. The contents of Fred’s question are now permanently displayed in the comments section underneath the photo.
