### ISSUE TITLE
10. Member inserts sponsored item in photo (TJ's)

### ISSUE THREAD

**Issue by janjakovacevic** [david-fisher/320-S19-Track2#14]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Steveo539** [comment]
Fred is a fan of the popular soda beverage Barry’s Red Cola, as well as a member of Members Only. Fred recently posted a photo of his latest beach trip to the Members Only home feed. Fred notices something, what would really make this picture awesome is some Barry’s Red Cola. Fred decides to use the ‘Add Content’ button on his beach photo to insert a picture of a can of Barry’s Red Cola next to him in the original photo. Fred then selects the ‘Save’ option in the location where the ‘Add Content’ button once was. Fred’s original photo is now displayed on the Members Only home feed with the can of Barry’s Red Cola in the location he selected.
