### ISSUE TITLE
11. Member unfollows a member (cannot unfollow a member that you invited) (TJ's)

### ISSUE THREAD

**Issue by janjakovacevic** [david-fisher/320-S19-Track2#15]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Steveo539** [comment]
Fred is a member of Members Only. One of the people Fred is following, Chad, has been annoying him lately. Fred did not invite Chad to the Members Only community. Fred decides that he no longer wants to see anything Chad does, and will remove him from his life entirely. Fred selects the ‘Unfollow’ button on Chad’s profile to stop displaying Chad’s posts and comments on Members Only from Fred’s home feed. After selecting the ‘Unfollow’ button, Fred clicks on the ‘Home’ menu on the taskbar at the top of his screen to return to the home page. Fred notices that all of Chad’s posts that were once on his feed are no longer there. From now on, any of Chad’s activity will be hidden to Fred unless Fred decides to follow Chad again.
