### ISSUE TITLE
12. Member accepts TOS (terms of service) (TJ's)

### ISSUE THREAD

**Issue by janjakovacevic** [david-fisher/320-S19-Track2#16]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Steveo539** [comment]
Fred recently received an invite to Members Only by an existing member. Fred then accepted the invite request via email and is prompted to the registration page. After entering all fields on the registration page, Fred notices a section at the bottom of the registration page about the ‘Terms of Service’ agreement. Embedded in the headline of the ‘Terms of Service’ area is a hyperlink to the full Terms of Service document. Underneath the hyperlink is a check box field besides the text ‘I accept the Terms of Service.’ Fred selects this button on the registration page and then clicks the ‘Proceed to Payment’ button on the lower right side of the page. Fred then enters the payment page, thus completing the first step of the registration process.
