### ISSUE TITLE
13. Member verifies credit card charge amount (input in the website) (TJ's)

### ISSUE THREAD

**Issue by janjakovacevic** [david-fisher/320-S19-Track2#17]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Steveo539** [comment]
Fred has recently completed the first and second step of registration. In the second step of the registration process, Fred was asked to enter his credit card information in the payment page.  After filling out all of his credit card information and selecting ‘Enter,’ Fred was then displayed the message ‘Card charged, please verify the amount billed’ next to a text field. Fred then briefly closes the Members Only session on his device and opens up his bank account via an app. After noticing a $0.25 charge on his latest card, Fred then returns to the Members Only registration session he had minimized and enters ‘0.25’ into the text field and presses ‘Enter’ on his keyboard. The Members Only registration software then confirms the amount charged to Fred’s credit card matches the amount entered. After confirming a match, Fred then completes the Members Only registration process.
