### ISSUE TITLE
Where should we be inserting our Models?

### ISSUE THREAD

**Issue by walshdan9163** [david-fisher/320-S19-Track2#175]
Within the Django project, where should we put Model 2's classes? In particular, which files should we be inserting our Model into and if needed, between what lines should we insert it?

**Comment by Steveo539** [comment]
You can go ahead and place everything in the models.py file. If you think that your files will cause a lot of clutter you could make another file and link it in models.py. I'm not going to be too picky about where you should put it in the file, just at the bottom to avoid merge conflicts.

**Comment by walshdan9163** [comment]
Sounds great, thank you.
