### ISSUE TITLE
18. Member loses points (TJ's)

### ISSUE THREAD

**Issue by janjakovacevic** [david-fisher/320-S19-Track2#22]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by kgill55** [comment]
The only way to lose points is to send a failed invite, other than that everything you do on the platform is gaining you points. So this issue could just be a simpler task of another story like "New member does not accept invitation and therefore the member who sent the invite loses points." Or whatever. It's good to be more specific with these stories.

**Comment by wkhammond** [comment]
I agree. Will leave this one blank for the time being.
