### ISSUE TITLE
Heroku mad

### ISSUE THREAD

**Issue by david-fisher** [david-fisher/320-S19-Track2#230]
Heroku sez (in multiple emails to me...):

A deployment for members-only-torch-jugglers failed due to a release phase command in release v27. To inspect the failure, check your release phase log in the dashboard or run 'heroku releases:output v27' in the CLI.If you wish to retry the release, you can use the release retry CLI plugin.
--

From the Release log:
Operations to perform:
  Apply all migrations: admin, auth, authtoken, contenttypes, members_only, sessions
Running migrations:
  No migrations to apply.
./release.sh: 4: ./release.sh: npm: not found
./release.sh: 5: ./release.sh: npm: not found

**Comment by JacksonWeber** [comment]
Fixed the bug. It looks like Heroku was missing the heroku/nodejs buildpack and therefore couldn't understand the `npm` command.
