### ISSUE TITLE
20. Member signs out (TJ's)

### ISSUE THREAD

**Issue by janjakovacevic** [david-fisher/320-S19-Track2#24]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by wkhammond** [comment]
Member Pam wants to log out of Members Only so her boyfriend can use the computer:
- Pam is logged in, and on the home page
- Pam clicks on the logout button
- Server logs out the user and disables any cookies
- Pam is returned to login page and her boyfriend logs in (goal achieved)
