### ISSUE TITLE
21. New member rejects (time out after 4 days) invitation (TJ's)

### ISSUE THREAD

**Issue by janjakovacevic** [david-fisher/320-S19-Track2#25]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by JacksonWeber** [comment]
Fred wants to invite a new member to Member's Only.

Fred sends out the invite to the friend he wants to invite via email.

The friend does not sign up with the invite for 4 days, and the invite expires, docking points from Fred. (goal achieved)
