### ISSUE TITLE
22. System sends usage data (TJ's)

### ISSUE THREAD

**Issue by janjakovacevic** [david-fisher/320-S19-Track2#26]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by JacksonWeber** [comment]
System wants to update the database with new member information.

**Comment by JacksonWeber** [comment]
This one should be reviewed and have more detail added so that we can properly attempt to merge our user stories with non-functional requirements
