### ISSUE TITLE
25. Member posts a shortened url/link (TJ's)

### ISSUE THREAD

**Issue by janjakovacevic** [david-fisher/320-S19-Track2#29]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by JacksonWeber** [comment]
Fred wants to post a link within a text-based post on Member's Only. 

Fred posts writes a link to a valid URL within his post or comment.

The system must recognize this link and send it to be shortened with our url shortener.

Fred's post or comment appears with the properly shortened link. (goal achieved)
