### ISSUE TITLE
Member follows/unfollows another member (Team Alt-F4)

### ISSUE THREAD

**Issue by jm48** [david-fisher/320-S19-Track2#3]
Members can follow another member.
Members can unfollow another member that they are following.

**Comment by nanglo123** [comment]
-Members also have the capability to follow idols. 

-Members cannot unfollow the members that they invited. 

-By following somebody, members can see all their previous and any future photos, comments, and posts.

**Comment by kgill55** [comment]
Clarification:

**You are always following everyone**. That's the default setting. You can only unfollow members that you didn't personally invite. 

I guess that also means when you unfollow someone you can re-follow them back? That's iffy. Could ask customer for clarification, won't be hard to implement either way.
