### ISSUE TITLE
26. Member forgets their login credentials (TJ's)

### ISSUE THREAD

**Issue by janjakovacevic** [david-fisher/320-S19-Track2#30]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by JacksonWeber** [comment]
Fred enters incorrect login information in the sign in fields. 

Fred navigates to the "Forgot your Password" link providing him with instructions for recovering his account's password.

Fred can then choose to ask the system to send a new password to his email account.

The system sends a newly created password to the email address linked to Fred's account.

The system must also update Fred's password value in the database entry linked to his account.

Fred can then return to the Member's Only sign in page and enter his new login information to access his account. (goal achieved)
