### ISSUE TITLE
27. Potential member can view the advertisement page (TJ's)

### ISSUE THREAD

**Issue by janjakovacevic** [david-fisher/320-S19-Track2#31]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by JacksonWeber** [comment]
A potential member wants to view the landing page of Member's Only.

They navigate using their web browser to the landing page that provides the website's name, an option to log in, and informs them that they must be invited by a member to create an account. (goal achieved)

*Note: "Potential member" is used intentionally here, signaling that they are not yet an individual member with a recognized name by Member's Only*
