### ISSUE TITLE
28. Owner creates admin (TJ's)

### ISSUE THREAD

**Issue by janjakovacevic** [david-fisher/320-S19-Track2#32]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by minaalexandra96** [comment]
Owner Clyde wants to add a new admin, Archibald
Owner Clyde logs into superuser account
Clyde creates new account the normal way Members do, but can bypass any step such as address and credit card input
Clyde sets the account to "admin account" on a later step (other option is "idol") - this gives the admin account more privileges than Members but less than the superuser account
Archibald now has an admin account with no credit card or address attached
