### ISSUE TITLE
29. Owner deletes data (TJ's)

### ISSUE THREAD

**Issue by janjakovacevic** [david-fisher/320-S19-Track2#33]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by minaalexandra96** [comment]
Owner Clyde logs into their “superuser” account
EVERY item / entity has a “delete” button (photos, posts, comments, accounts)
Clyde sees a post that offends him and hits the "delete" button on the post
When button is clicked, there’s no going back - the data is permanently deleted from the site and removed from Clyde's page view
