### ISSUE TITLE
30. Member views other profiles (TJ's)

### ISSUE THREAD

**Issue by janjakovacevic** [david-fisher/320-S19-Track2#34]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by minaalexandra96** [comment]
Gertrude is scrolling through the homepage and comes across Larrie's post
Gertrude wants to view Larrie's profile
Gertrude clicks on Larrie's name on the post
The link takes Gertrude to Larrie's profile
Larrie's profile displays his name and address
Now Gertrude can stalk Larrie while he sleeps
