### ISSUE TITLE
31. Member views their own profile (TJ's)

### ISSUE THREAD

**Issue by janjakovacevic** [david-fisher/320-S19-Track2#35]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by minaalexandra96** [comment]
Bertha wants to view her profile
Bertha clicks on the "Profile" tab
This brings her to a page displaying her name and address, and the navbar at the top now has a "Settings" tab
