### ISSUE TITLE
2. Member invites a new member (TJ's)

### ISSUE THREAD

**Issue by janjakovacevic** [david-fisher/320-S19-Track2#6]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by wkhammond** [comment]
You should add the scenario for if the invitation is not accepted (fits better here than in its own story)

**Comment by janjakovacevic** [comment]
Alex is a member of Member Only. Alex has collected enough points and now wants to invite his friend Larry to join Members Only. Alex is at the top of the home page of Members Only website. He goes to his profile by clicking on his name. He clicks on 'invite a new member' button that allows him to send an email to Larry with an invitation link. He types in Larry's email and clicks on 'send an invitation'. Larry receives an invitation.

2 scenarios are possible once Larry receives an invitation:
- Larry chooses to accept the invitation. Once he registers, his friend Alex receives 50 points
- Larry chooses to decline the invitation. His friend Alex loses 100 points.
