### ISSUE TITLE
Setup Heroku to deploy from class git repo

### ISSUE THREAD

**Issue by JacksonWeber** [david-fisher/320-S19-Track2#72]
I have a Heroku instance that deploys that deploys code from the develop branch. I have sent you an email invite from Heroku to administer the project hosting. Once you are an administrator you can navigate on Heroku to disconnect the current fork and connect the `develop` branch on the class repo. I've sent the invite to the email listed on your github account.

Example: http://prntscr.com/msgznm

**Comment by david-fisher** [comment]
Insufficient instruction. Don't expect me to learn how to use your tool. If you require me to take an action, provide the complete set of steps to perform (not a web link to an example).

I created the requested account. It appears it is already connected to the develop branch. So, try again, what, exactly, do you want me to do with your software tool?

**Comment by JacksonWeber** [comment]
Apologies for the prior vagueness. Here is a more detailed set of instructions for connecting Heroku to Integration Track 2's repository.

- Start at https://id.heroku.com/login

- Once you have made an account, enter your email and password into the fields on the login page.

- From the page you are navigated to, click the members-only-torch-jugglers app.

- From the page you are navigated to (Overview), click the "deploy" button on the tab bar.

- From the page you are navigated to, next to "Deployment method" select the "GitHub" option.

- Next to "Connect to GitHub", sign in to your GitHub account and use the search bar to find and select the integration track 2 repository. Once you have selected it, click the "connect" button.

**Comment by david-fisher** [comment]
Thank you for complete instruction. I look forward to hearing about your team's deployment tool choice in your next presentation.
