### ISSUE TITLE
Draft the Image Filtering HLD

### ISSUE THREAD

**Issue by frigorific44** [david-fisher/320-S19-Track2#88]
Draft the high level design which involves image filtering. This includes class diagrams (or some reference to any relations between classes) and the public API for all classes, including brief descriptions of functionality. Refer to the relevant User Stories to verify complete functionality. Please complete this in time for reviewal at our next meeting (probably on Tuesday).

**Comment by tcmanning** [comment]
Will be adding corresponding user stories to the doc on Monday. Please let me know if you want any changes made to the class diagram before the meeting as well.
